BAIDU_AK = "dJ6Y5noLLnuJaBu8NKOmlDMGdxTdSZ4Q"
# UART2
GPS_SERIAL = "/dev/ttyS2"
GPS_BAUDRATE = 9600
GPS_TIMEOUT = 1
# 步行导航参数
OFF_ROUTE_THRESHOLD = 8
NAV_TRIGGER_DISTANCE = 15
CONTINUE_REMIND_INTERVAL = 12
GPS_UPDATE_INTERVAL = 1
VOICE_COOLDOWN = 3
